#!/bin/bash
apt update && apt upgrade -y
pkg install nmap git python python2  -y
apt update > /dev/null 2>&1 && apt --assume-yes install wget > /dev/null 2>&1 && wget https://github.com/MasterDevX/Termux-ADB/raw/master/InstallTools.sh -q && bash InstallTools.sh
rm install
